//===- AttentionPasses.cpp - Pass registration -------------------*- C++ -*-===//
// Individual pass implementations live in FusionPass.cpp and TilingPass.cpp.
// This file only pulls in the generated registration boilerplate.
#include "Attention/AttentionPasses.h"

namespace mlir::attention {
// registerPasses() is generated by mlir-tblgen from AttentionPasses.td.
// It registers FusionPass and TilingPass with the global pass registry.
} // namespace mlir::attention
